In [2]:
import numpy as np

### The important functions are as follows

In [39]:
a = np.array([(1.5, 2, 3), [4, 5, 6]]) # to make an array with custom input
print(a)                               # the brackets dont matter '(' and '[' are same

# the data type of the elements can be specified at creation by the dtype attribute
# to use python data type just type int or float, etc
# to use numpy data type use np.int64 , etc
a = np.array([(1.5, 2, 3), [4, 5, 6]], dtype = np.complex64)  
print(a) 

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5+0.j 2. +0.j 3. +0.j]
 [4. +0.j 5. +0.j 6. +0.j]]


In [ ]:
#NUMPY ARRAYS CAN BE SLICED LIKE REGULAR ARRAYS
a = np.arange(9).reshape(3,3)
a[::1] 

#FOR ACCESSING COLUMNS MAKE THE END INDEX ','
a = np.arange(9).reshape(3,3)
a[:,:1] 

In [30]:
a = np.arange(0,9,1) # makes a 1d array of integers in range (0,10)
print(a)              # can be modified with start and end and step 


[0 1 2 3 4 5 6 7 8]


In [41]:
# a better alternative of arange function is the linspace
# returns an array of floats including the start and end indexes of 3 elements
# with equal spacing
print(np.linspace(0,9,3)) 

[0.  4.5 9. ]


In [47]:
#used to create and array of zeros
# we define the size of the array inside the fuction
np.zeros((2,3,5)) # VALUES MUST BE PASSED AS A TUPLE

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [46]:
#used to create and array of ones
# we define the size of the array inside the fuction
np.ones((2,3,5)) # VALUES MUST BE PASSED AS A TUPLE

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [18]:
a.shape # tells the size of the array, not to be confused with the .reshape(a,b) function

(9,)

In [19]:
a.ndim # only tells the number of dimensions

1

In [20]:
a.size #similar to the length functions gives the number of elements

9

In [21]:
a = a.reshape(3,3) # can change the size and the dimension of the array
print(a)           # will give error if the number of elements is off

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
a.dtype.name # gives the data type of the element
             # use .name to extract the string with the info of the data type


'int64'

### Lab Questions

In [49]:
'''
1. Convert a 1-D array into a 2-D array with 3 rows.
Start with:
Assign-1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
Desired output:
[[ 0, 1, 2]
[3, 4, 5]
[6, 7, 8]]
'''
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
'''
2. Replace all odd numbers in the given array with -1
Start with:
Assign-2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:
[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]
'''

a = np.arange(10)
print(a)

# print(np.mod(a,2)!=0) this function returns an array of boolean values satisfing the condtion

a[np.mod(a,2) != 0] = -1 # for all values that are odd, -1 will be replaced
# a[a%2!=0] = -1 will give the same output
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
'''
3. Find the positions of:

elements in x where its value is more than its corresponding element in y, and 
elements in x where its value is equals to its corresponding element in y.

Start with these:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

Desired output:
(array([1, 2, 4, 5, 6, 7, 8, 9]),) and (array([0]),)
'''
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.array([21, 7, 3, 45, 10, 29, 1, 4, 37])
 
# we can use comparison operators in numpy which will compare with each element and return an array
# DO CHECK THE RESULT WITH THE USE OF RESHAPE

    
print(np.where(x > y))
print(np.where(x == y))

(array([6, 7], dtype=int64),)
(array([2], dtype=int64),)


In [8]:
'''
4. Extract the first four columns of this 2-D array.
Start with this: 
Assign-4= np.arange(100).reshape(5,-1)
 
Desired output:
[[ 0 1 2 3]
[20 21 22 23]
[40 41 42 43]
[60 61 62 63]
[80 81 82 83]]
'''

a = np.arange(100).reshape(5,-1) # -1 is used as a placeholder to calculate the columsn based on the length of the array 
print(a)
a[:, 0 : 4] 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43]])

### Additional Questions

In [90]:
'''
1. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).
Sample of desired output:
[36, 30, 36, 38, 31, 35, 36, 30, 32, 34]
'''
x = np.random.randint(low=30, high=40, size=10)
x

array([33, 37, 35, 33, 31, 32, 31, 38, 36, 32])

In [113]:
'''
2. Consider the following matrices :
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and   B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
Write a python program to perform the following using Numeric Python (numpy).
i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
iii) Product of two matrices A and B, and print the resultant matrix D
iv) Sort the elements of resultant matrix C and print the resultant Matrix E.                           
v) Transpose the Matrix E and print the result

'''
a = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 10)))
b = np.array(((7, 8, 10) ,(4, 5, 6), (1, 2, 3)))


#2 i
c=a+b
e=a-b
print(c)
print(e)

#2 ii
print(a.sum())
print(b.sum(axis = 0)) # axis 0 is for columns in the sum() function
print(c.sum(axis = 1)) # axis 1 is for rows in the sum() function

#2 iii
d = np.dot(a,b)
print(d)

#2 iv
e = np.sort(c, axis = 0) # axis can also be specified
print(e)

#2 v
print(np.transpose(e))

[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]
